version: '3.8'

services:
  mysql-db:
    image: mysql:latest
    container_name: library_mysql
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: library_user
      MYSQL_PASSWORD: library_password
      MYSQL_DATABASE: library_db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5

volumes:
  db_data:
