
services:
  mysql-db:
    image: mysql:latest
    container_name: library_mysql
    restart: always
    ports:
      - "3307:3306"
#      volumes:
#        - db_data:/var/lib/mysql
#      networks:
#        -library_network

    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: library_user
      MYSQL_PASSWORD: library_password
      MYSQL_DATABASE: library_db
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -u root -p $$MYSQL_ROOT_PASSWORD
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
volumes:
  db_data:
networks:
  library_network:
    driver: bridge
